### ISSUE TITLE
Google robot check

### ISSUE THREAD

**Issue by mikestephens** [hash-gaming/slackproval#10]
Implement a google robot check so we know requesting people aren’t bots

**Comment by YashdalfTheGray** [comment]
https://richonrails.com/articles/adding-recaptcha-to-your-rails-application

**Comment by YashdalfTheGray** [comment]
Will pick this up after the code of conduct.

**Comment by mikestephens** [comment]
Lets see if we can make this optional behind an env for the sake of being lightweight in setup
